In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
validating = requests.get('https://www.imdb.com/chart/toptv/?sort=ir,desc&mode=simple&page=1')
validating.status_code

200

In [3]:
# Parsing Content from url
tv_shows = BeautifulSoup(validating.text,'html.parser')

In [4]:
Show_name= tv_shows.find_all('td',{'class':'titleColumn'})
rating= tv_shows.find_all('td',{'class':'ratingColumn imdbRating'})
name =[]
year=[]
show_rating=[]
user_rated_that_movie=[]
url=[]
top_actors=[]
for i in range(len(Show_name)):
    name.append(Show_name[i].text.strip().replace(" ","").split('\n')[1])
    year.append(Show_name[i].text.strip().replace(" ","").split('\n')[2].replace('(',"").replace(')',""))
    show_rating.append(rating[i].text.strip())
    for body in tv_shows.find_all('td',{'class':'ratingColumn imdbRating'}):
            if body.find('strong'):
                text= body.find('strong')
                title= text.get('title')
                x= title.split(" ")
                user_rated_that_movie.append(x[3])
    for body in tv_shows.find_all('td',{'class':'titleColumn'}):
            if body.find('a'):
                text= body.find('a')
                top_actor= text.get('title')
                #text_link=body.find('a')['href']
                #text_link='https://www.imdb.com/'+ text_link +'?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=12230b0e-0e00-43ed-9e59-8d5353703cce&pf_rd_r=BE897XJHS7BYFMFFPCRK&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=toptv&ref_=chttvtp_tt_2'
                top_actors.append(top_actor)

In [6]:
shows_data=pd.DataFrame(list(zip(name,year,show_rating,user_rated_that_movie,top_actors)),columns=['Name','Release year','Show_rating','No_users_rated','Top actors'])
shows_data

,Name,Release year,Show_rating,No_users_rated,Top actors
0,PlanetEarthII,2016,9.4,"112,238","David Attenborough, Chadden Hunter"
1,BreakingBad,2008,9.4,"1,682,813","Bryan Cranston, Aaron Paul"
2,PlanetEarth,2006,9.4,"179,598","Sigourney Weaver, David Attenborough"
3,BandofBrothers,2001,9.4,"419,222","Scott Grimes, Damian Lewis"
4,Chernobyl,2019,9.3,"662,960","Jessie Buckley, Jared Harris"
...,...,...,...,...,...
245,JesusofNazareth,1977,8.4,"21,720","Robert Powell, Olivia Hussey"
246,Flames,2018,8.4,"28,216","Ritvik Sahore, Tanya Maniktala"
247,Luther,2010,8.4,"132,770","Idris Elba, Dermot Crowley"
248,BirBaskadir,2020,8.4,"25,794","Öykü Karayel, Fatih Artman"
249,ThePrisoner,1967,8.4,"13,713","Patrick McGoohan, Angelo Muscat"